"""
Django settings for RiftValley project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import environ
import os
from pathlib import Path

from whitenoise.storage import CompressedManifestStaticFilesStorage

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, True))
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-019yyjws5m8cc+$8x**(+$#k0)$!jug=+h2rvb#p5e3ee6ecy=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',       # ← add this
    'rest_framework',
    'rest_framework_gis',
    'Truck',
    'bootstrap4',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Truck.middleware.ProfileMiddleware',
]


ROOT_URLCONF = 'RiftValley.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'RiftValley.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# ── Database: switch from SQLite to PostGIS ──────────────────────────────────
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=env('DATABASE_URL'),
        engine='django.contrib.gis.db.backends.postgis',
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Where collectstatic puts files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'Truck/static'),  # Your app-specific static files
]

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Match the actual login URL in your urls.py
LOGIN_URL = '/sign_in/'
LOGIN_REDIRECT_URL = '/'

# Ensure sessions persist properly
SESSION_COOKIE_NAME = 'rvc_sessionid'  # custom name avoids conflicts with other local projects


AUTHENTICATION_BACKENDS = [
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

SOCIAL_AUTH_FACEBOOK_KEY = "7448007858649860"
SOCIAL_AUTH_FACEBOOK_SECRET = "c4b7a040a0ce0fee313f7aeccfeaf05d"
SOCIAL_AUTH_FACEBOOK_SCOPE = ['EMAIL']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields':'id, name, email'
}
#stripe configuration
STRIPE_API_PUBLIC_KEY = "pk_test_51P7iQvH8HmEJ2HLLyRBv8smOWYlHBxDIQ97M3GfxOW5KMDINXLG64rCn8wzvwbiUJWJGpY4WPsGx7PG2gQw78laF0019acYxQg"
STRIPE_API_SECRET_KEY = "sk_test_51P7iQvH8HmEJ2HLLpfyWM4BV9Ghi88xDz8uTEmrkLkqm3HU7hCI2av1f3TvzxOMi9a1rgkzNtTvgljXBLE5ii3r500ECCZtr8T"

#key configuration
GOOGLE_MAP_API_KEY = "AIzaSyAF6hd7oJfxsA3fBpxWnYuevkn8booYrUE"

#paypal configuration
PAYPAL_MODE = "sandbox"
PAYPAL_CLIENT_ID = "AdnNxR97JUUj45PSvU2fPD5C7Lj7nlIY_vqD2zWM9y-XNnZKhwpJHzRHP4ecF4hXBCEJQZCB9dX8XhHM"
PAYPAL_CLIENT_SECRET = "ECzjHyP3wjj8xismmtBYgkGB72fo2gnug5dw7GZOOGpVkHEyYxzi7IFVGTboZv4XyaQUYlBMmz5am3D4"


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Email setup codes for password reset
EMAIL_BACKEND    = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST       = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT       = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS    = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER  = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

#email setup (invoice and job acceptance) to Customer and (job created) to owner.
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='J&N Collections <noreply@example.com>')
OWNER_EMAIL = env('OWNER_EMAIL', default='joseph.gikuru@students.jkuat.ac.ke')

NOTIFICATION_URL = "https://RiftValleyCarrier.pythonanywhere.com/"


# List of trusted origins for CSRF protection
CSRF_TRUSTED_ORIGINS = [
    'https://RiftValleyCarrier.pythonanywhere.com/',
    # Add any other ngrok URLs if necessary  running ngrok command./ngrok http 8000

]

# ── Celery ───────────────────────────────────────────────────────────────────
CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# ── Google Maps (already in your project) ───────────────────────────────────
GOOGLE_MAP_API_KEY = env('GOOGLE_MAP_API_KEY', default='')

# ── OSRM (Phase 2) ─────────────────────────────────────────────────────────
OSRM_BASE_URL = env('OSRM_BASE_URL', default='')

# RiftValley/settings.py — add these session settings

# ── Session configuration ─────────────────────────────────────────────────────
# Keep couriers logged in for 30 days — critical for mobile courier use
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30        # 30 days in seconds

# Do NOT expire when browser closes — courier might switch apps while driving
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Save session on every request so the 30-day timer resets with activity
SESSION_SAVE_EVERY_REQUEST = True

# On localhost (http) this MUST be False — True means cookie only sent over https
SESSION_COOKIE_SECURE = False

# Makes session cookie inaccessible to JavaScript (security best practice)
SESSION_COOKIE_HTTPONLY = True

# SameSite Lax allows normal navigation while blocking CSRF from external sites
SESSION_COOKIE_SAMESITE = 'Lax'

# ── CSRF configuration ────────────────────────────────────────────────────────
# Same logic — False for http localhost, True in production
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False    # Must be False so JS can read it for fetch() calls
CSRF_COOKIE_SAMESITE = 'Lax'