"""
Django settings for RiftValley project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-019yyjws5m8cc+$8x**(+$#k0)$!jug=+h2rvb#p5e3ee6ecy='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','https://6e64-102-213-251-138.ngrok-free.app/']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Truck',
    'bootstrap4',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Truck.middleware.ProfileMiddleware',
]

ROOT_URLCONF = 'RiftValley.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'RiftValley.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# settings.py

# Define the path to your static root directory
#STATIC_ROOT = '/Users/gikur/HTMLdjangoProjects/LOGISTICS/RiftValley/RiftValley/Truck/static_root/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Define the path to your additional static directory
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'Truck/static'),
]


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/sign_in/'
LOGIN_REDIRECT_URL = '/'


AUTHENTICATION_BACKENDS = [
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

SOCIAL_AUTH_FACEBOOK_KEY = "7448007858649860"
SOCIAL_AUTH_FACEBOOK_SECRET = "c4b7a040a0ce0fee313f7aeccfeaf05d"
SOCIAL_AUTH_FACEBOOK_SCOPE = ['EMAIL']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields':'id, name, email'
}
#stripe configuration
STRIPE_API_PUBLIC_KEY = "pk_test_51P7iQvH8HmEJ2HLLyRBv8smOWYlHBxDIQ97M3GfxOW5KMDINXLG64rCn8wzvwbiUJWJGpY4WPsGx7PG2gQw78laF0019acYxQg"
STRIPE_API_SECRET_KEY = "sk_test_51P7iQvH8HmEJ2HLLpfyWM4BV9Ghi88xDz8uTEmrkLkqm3HU7hCI2av1f3TvzxOMi9a1rgkzNtTvgljXBLE5ii3r500ECCZtr8T"

#key configuration
GOOGLE_MAP_API_KEY = "AIzaSyAF6hd7oJfxsA3fBpxWnYuevkn8booYrUE"

#paypal configuration
PAYPAL_MODE = "sandbox"
PAYPAL_CLIENT_ID = "AdnNxR97JUUj45PSvU2fPD5C7Lj7nlIY_vqD2zWM9y-XNnZKhwpJHzRHP4ecF4hXBCEJQZCB9dX8XhHM"
PAYPAL_CLIENT_SECRET = "ECzjHyP3wjj8xismmtBYgkGB72fo2gnug5dw7GZOOGpVkHEyYxzi7IFVGTboZv4XyaQUYlBMmz5am3D4"


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'gikurujoseph53@gmail.com'
EMAIL_HOST_PASSWORD = 'oegc obda mlfy oulv'

#email setup (invoice and job acceptance) to Customer and (job created) to owner.
DEFAULT_FROM_EMAIL = 'gikurujoseph53@gmail.com'
OWNER_EMAIL = 'joseph.gikuru@students.jkuat.ac.ke'

NOTIFICATION_URL = "https://1208-102-213-251-138.ngrok-free.app/"


# List of trusted origins for CSRF protection
CSRF_TRUSTED_ORIGINS = [
    'https://6e64-102-213-251-138.ngrok-free.app',
    # Add any other ngrok URLs if necessary  running ngrok command./ngrok http 8000

]