# Generated by Django 3.2.25 on 2024-04-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0002_auto_20240420_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='paypal_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
