# Generated by Django 3.2.25 on 2024-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0011_auto_20240425_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(upload_to='job/photo/'),
        ),
    ]
