# Generated by Django 5.0.6 on 2024-05-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0012_alter_job_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
