# Generated by Django 5.0.6 on 2024-06-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0014_courier_paypal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='in', max_length=20),
        ),
    ]
