# Generated by Django 5.0.6 on 2024-06-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0016_courier_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='paypal_email',
        ),
    ]
