# Generated by Django 6.0.3 on 2026-03-26 16:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0017_remove_customer_paypal_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='courier',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='job',
            name='delivery_lat',
        ),
        migrations.RemoveField(
            model_name='job',
            name='delivery_lng',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pickup_lng',
        ),
        migrations.AddField(
            model_name='courier',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='is_on_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='job',
            name='pickup_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Entered zone'), ('exit', 'Exited zone')], max_length=10)),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('trigger_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='Truck.courier')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Truck.deliveryzone')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('speed_kmh', models.FloatField(default=0, null=True)),
                ('heading', models.FloatField(default=0, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='Truck.courier')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['courier', 'recorded_at'], name='Truck_couri_courier_657a8d_idx')],
            },
        ),
    ]
