# Generated by Django 6.0.3 on 2026-04-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0018_deliveryzone_remove_courier_lat_remove_courier_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
