# Generated by Django 6.0.3 on 2026-04-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0019_courier_current_lat_courier_current_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='current_lng',
        ),
    ]
