# Generated by Django 6.0.3 on 2026-05-09 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0020_remove_courier_current_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierZoneState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('outside', 'Outside zone'), ('dwell', 'Potentially entering (dwell)'), ('inside', 'Confirmed inside zone')], default='outside', max_length=10)),
                ('consecutive_inside', models.IntegerField(default=0)),
                ('consecutive_outside', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AddField(
            model_name='courier',
            name='smoothed_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='smoothed_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courierzonestate',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_states', to='Truck.courier'),
        ),
        migrations.AddField(
            model_name='courierzonestate',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_states', to='Truck.deliveryzone'),
        ),
        migrations.AddIndex(
            model_name='courierzonestate',
            index=models.Index(fields=['courier', 'state'], name='Truck_couri_courier_c73f1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courierzonestate',
            unique_together={('courier', 'zone')},
        ),
    ]
