# Generated by Django 6.0.3 on 2026-05-09 21:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0021_courierzonestate_delete_owner_delete_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='confirmation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
