# Generated by Django 6.0.3 on 2026-05-09 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0023_populate_confirmation_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
