# Generated by Django 6.0.3 on 2026-05-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0024_alter_job_confirmation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Courier profile photo — shown in the app and job pages.', null=True, upload_to='courier/avatars/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('van', 'Van'), ('truck', 'Truck'), ('pickup', 'Pickup Truck'), ('motorcycle', 'Motorcycle'), ('car', 'Car')], help_text='Vehicle type used for deliveries.', max_length=50),
        ),
    ]
