# Generated by Django 5.2.14 on 2026-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0025_courier_avatar_courier_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='license_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courier',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='verification_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='courier',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
