# Generated by Django 5.2.14 on 2026-05-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0026_courier_face_verified_courier_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='verification_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='not_started', max_length=20),
        ),
    ]
