# Generated by Django 6.0.3 on 2026-05-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0027_alter_courier_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='face_verified',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='license_class',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='license_expiry',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='license_photo',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='selfie_photo',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='verification_attempts',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='verification_score',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='verified_at',
        ),
    ]
