# Generated by Django 6.0.3 on 2026-05-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0028_remove_courier_face_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='license_class',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='courier',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='courier',
            name='license_photo',
            field=models.ImageField(blank=True, help_text="Front of the courier's driver's licence.", null=True, upload_to='courier/licenses/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='selfie_photo',
            field=models.ImageField(blank=True, help_text='Selfie used for face matching against the licence photo.', null=True, upload_to='courier/selfies/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courier',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='verification_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='courier',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('failed', 'Failed — resubmit')], default='unverified', help_text='Current driver licence verification status.', max_length=20),
        ),
        migrations.AddField(
            model_name='courier',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
