# Generated by Django 6.0.3 on 2026-05-20 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0029_courier_face_verified_courier_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('notified', 'FCM Notified'), ('accepted', 'Job Accepted'), ('timeout', 'Timed Out (90s)'), ('no_couriers', 'No Couriers Available'), ('exhausted', 'All Attempts Exhausted'), ('already_accepted', 'Already Accepted'), ('fcm_failed', 'FCM Push Failed')], max_length=30)),
                ('attempt_number', models.IntegerField(default=1)),
                ('distance_km', models.FloatField(blank=True, help_text='Distance from courier to pickup (km)', null=True)),
                ('elapsed_seconds', models.FloatField(blank=True, help_text='Seconds since dispatch started', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='Truck.courier')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='Truck.job')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='Truck_dispa_job_id_b2ffe8_idx')],
            },
        ),
    ]
