# Generated by Django 6.0.3 on 2026-05-22 21:06

import Truck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0030_dispatchlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('subject', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('delivery', 'Delivery Issue'), ('billing', 'Billing & Payments'), ('tracking', 'Tracking & GPS'), ('courier', 'Courier Enquiry'), ('technical', 'Technical Support'), ('general', 'General Enquiry'), ('feedback', 'Feedback')], default='general', max_length=30)),
                ('message', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('ticket_number', models.CharField(default=Truck.models.generate_ticket_number, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('replied', 'Replied'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes — not visible to sender')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chatbot_session_id', models.CharField(blank=True, help_text='Reserved for AI chatbot session linkage', max_length=120)),
            ],
            options={
                'ordering': ['-is_urgent', '-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='Truck_conta_status_f87f3c_idx')],
            },
        ),
    ]
