# Generated by Django 6.0.3 on 2026-05-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0031_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='classification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('flagged', 'Flagged — admin review'), ('skipped', 'Skipped')], default='pending', help_text='Status of AI goods classification for this job', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='fragility_flag',
            field=models.BooleanField(default=False, help_text='True if AI detected fragile item — shown to courier'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_flagged_prohibited',
            field=models.BooleanField(default=False, help_text='True if prohibited goods detected — blocks job until admin review'),
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID for debugging', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('flagged', 'Flagged — prohibited items detected')], default='pending', max_length=20)),
                ('category_suggestion', models.CharField(blank=True, max_length=50)),
                ('category_confidence', models.FloatField(default=0.0)),
                ('item_name_suggestion', models.CharField(blank=True, max_length=255)),
                ('low_confidence', models.BooleanField(default=False, help_text='True when CLIP confidence < 0.35')),
                ('size_suggestion', models.CharField(blank=True, max_length=20)),
                ('size_reliable', models.BooleanField(default=True)),
                ('fragility_score', models.FloatField(default=0.0)),
                ('is_fragile', models.BooleanField(default=False)),
                ('prohibited_detected', models.BooleanField(default=False)),
                ('prohibited_items', models.JSONField(default=list, help_text='List of detected prohibited items with confidence scores')),
                ('prohibited_reason', models.TextField(blank=True)),
                ('processing_time_s', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('raw_results', models.JSONField(default=dict, help_text='Full raw output from all pipeline stages (debug)')),
                ('chatbot_session_id', models.CharField(blank=True, help_text='Reserved for future AI chatbot session linkage', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='Truck.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
