# Generated by Django 6.0.3 on 2026-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0032_job_classification_status_job_fragility_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='goods_type',
            field=models.CharField(choices=[('standard', 'Standard Goods'), ('fragile', 'Fragile / Delicate'), ('medical', 'Medical Supplies'), ('artwork', 'Artwork / Antiques'), ('perishable', 'Perishables')], default='standard', help_text='Affects pricing surcharge and courier handling instructions', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='price_base_fare',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='job',
            name='price_fuel_surcharge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='job',
            name='price_goods_surcharge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='job',
            name='price_mileage_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='job',
            name='size',
            field=models.CharField(choices=[('small', 'Small — Cargo Van (up to 150 lbs)'), ('medium', 'Medium — Box Truck (150 lbs to 10,000 lbs / ~5 tons)'), ('large', 'Large — Semi-Truck (10,000 lbs to 80,000 lbs / up to 36 tons)')], default='medium', max_length=20),
        ),
    ]
