# Generated by Django 6.0.3 on 2026-05-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0033_job_goods_type_job_price_base_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='weather_condition',
            field=models.CharField(blank=True, default='', help_text='WMO condition key: clear|drizzle|rain|heavy_rain|fog|snow|storm', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='weather_eta_multiplier',
            field=models.FloatField(default=1.0, help_text='ETA multiplier from weather at booking time, e.g. 1.12 for rain'),
        ),
        migrations.AddField(
            model_name='job',
            name='weather_icon',
            field=models.CharField(blank=True, default='fa-sun', help_text='FontAwesome icon class', max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='weather_label',
            field=models.CharField(blank=True, default='', help_text='Human-readable label, e.g. "Light Rain"', max_length=40),
        ),
    ]
